// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_LDyfuhzyVagwfgCQTxaw_MCFE7zgqxw',
    appId: '1:568928902692:web:c05c4d512a416e7e7a02b1',
    messagingSenderId: '568928902692',
    projectId: 'gameart-7c1a7',
    authDomain: 'gameart-7c1a7.firebaseapp.com',
    storageBucket: 'gameart-7c1a7.firebasestorage.app',
    measurementId: 'G-MPGC0RV9G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19rmRzNujVXIxLjJbXz1yBme5LdRGV04',
    appId: '1:568928902692:android:56c3f58361363b627a02b1',
    messagingSenderId: '568928902692',
    projectId: 'gameart-7c1a7',
    storageBucket: 'gameart-7c1a7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_LDyfuhzyVagwfgCQTxaw_MCFE7zgqxw',
    appId: '1:568928902692:web:83428e37a9369a067a02b1',
    messagingSenderId: '568928902692',
    projectId: 'gameart-7c1a7',
    authDomain: 'gameart-7c1a7.firebaseapp.com',
    storageBucket: 'gameart-7c1a7.firebasestorage.app',
    measurementId: 'G-Q0B8367XDJ',
  );
}
